import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MswProvider } from "@/providers/mswProvider";
import { QueryClientComponent } from "@/providers/queryClientProvider";
import { DrawerComponent } from "@/components/drawer";
import Box from "@mui/material/Box";
import { TaskContextProvider } from "@/providers/contextProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MswProvider>
          <QueryClientComponent>
            <TaskContextProvider>
              <Box
                sx={{
                  display: "flex",
                  width: "100%"
                  }}>
                <Box
                  component="div"
                  sx={{
                    width: 250
                  }}>
                  {/** ドロワー */}
                  <DrawerComponent />
                </Box>

                <Box
                  component="main"
                  sx={{
                    flexGrow: 1,
                    p: 3,
                    boxSizing: "border-box"
                    }}>
                  {children}
                </Box>
              </Box>
            </TaskContextProvider>
          </QueryClientComponent>
        </MswProvider>
      </body>
    </html>
  );
}
